# Generated by Django 3.0.8 on 2020-07-28 12:36
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('reconocimientos', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categorias',
            field=models.ManyToManyField(
                blank=True, to='reconocimientos.Categoria'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                         related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='menciones',
            field=models.ManyToManyField(
                blank=True, editable=False, to='reconocimientos.Mencion'),
        ),
        migrations.AddField(
            model_name='user',
            name='proyectos',
            field=models.ManyToManyField(
                blank=True, to='reconocimientos.Proyecto'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set',
                                         related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
