# Generated by Django 3.0.8 on 2020-07-28 12:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# flake8: noqa
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Puntuaciones',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
                ('codigo', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('dificultad', models.IntegerField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='autor_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realización', models.DateTimeField(
                    default=datetime.datetime.now, editable=False)),
                ('categoria', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='reconocimientos.Categoria')),
                ('emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='emisor', to=settings.AUTH_USER_MODEL)),
                ('puntuacion', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='reconocimientos.Puntuacion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='receptor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Menciones',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='puntuacion',
            field=models.ManyToManyField(
                blank=True, default=4, to='reconocimientos.Puntuacion'),
        ),
    ]
